### ISSUE TITLE
[#08] 혹시 중복되어있는 코드 없는지 확인합시다!

### ISSUE THREAD

**Issue by JIHAE-KIM** [JIHAE-KIM/SOFTWARE_JHS#11]
지해: panelmain, panelframe, connectdb
해연: panel01,panel02,panel03
수지: panel04

**Comment by haeyeonlee** [comment]
끙끙 넴 !거의다왔다

**Comment by SujiJang** [comment]
넵 확인했습니다!! 04에 connectdb 주석처리한 부분도 지웠습니다!
