### ISSUE TITLE
[#02_1]update텍스트필드 도와주세요~!

### ISSUE THREAD

**Issue by JIHAE-KIM** [JIHAE-KIM/SOFTWARE_JHS#4]
지금 텍스트창이 4개인데(id, 이름, 학과, 번호), 
update할때는 학생 id, 그리고 전화번호 부분만 텍스트 필드가 활성화 되어야합니다.~! 
어떻게 하면될까요???

**Comment by haeyeonlee** [comment]
그렇겠네요. 업데이트 수정해야 될 것 같습니다.

**Comment by SujiJang** [comment]
일단 비활성화 해보아용!!

**Comment by SujiJang** [comment]
일단 비활성해 해봅시다!!
