### ISSUE TITLE
[#04] student view

### ISSUE THREAD

**Issue by JIHAE-KIM** [JIHAE-KIM/SOFTWARE_JHS#6]
학생정보를 보여주는 코드를 추가하였습니다.
그런데, 학생정보를 아이디를 검색하여 그 학생만 볼수 있도록 하려면 어떻게 코드를 수정해야하나요??
도와주세요~!

**Comment by haeyeonlee** [comment]
아 지금은 그냥 전체 학생이 나오나요?

**Comment by haeyeonlee** [comment]
탭 메뉴 어때요? 구현 가능하신 분 있나요...?

**Comment by SujiJang** [comment]
sql에 조건을 달아 해당학생정보만 볼수 있도록 합시다!!

**Comment by haeyeonlee** [comment]
혹시 수지언니 가능하신가요? ㅠㅠ
