### ISSUE TITLE
[#04_1] tab 메뉴 구현이 결정되었습니다. 담당자는 수지언니로 합시다!

### ISSUE THREAD

**Issue by haeyeonlee** [JIHAE-KIM/SOFTWARE_JHS#7]
투표 결과 tab 메뉴 구현이 결정되었습니다. 
저희 담당자는 수지언니로 합시다! 수지언니 가능하신가요? 댓글달아주세요.

**Comment by JIHAE-KIM** [comment]
네! tab메뉴로 구성하는게 제일 좋을꺼 같아요! 수지언니가 탭메뉴 구성하면 저희가 기존에 했던 기능들을 추가해서 완성해 나가겠습니다!

**Comment by haeyeonlee** [comment]
assignee 수지언니로 변경했어요!

**Comment by SujiJang** [comment]
네 변경해보겠습니다!!
