### ISSUE TITLE
[#05] TabPanel을 이용해 기능을 나누고 클래스를 나누어 보았어요. 그런데....

### ISSUE THREAD

**Issue by SujiJang** [JIHAE-KIM/SOFTWARE_JHS#8]
기능별로 클래스를 나누고 탭프레임에서 불러오는데 클래스를 추가하는 과정에서 에러가 생겨요.
어떻게 불러와 추가할 수 있을까요??
![bug1](https://cloud.githubusercontent.com/assets/15049195/10867591/949528c0-80ad-11e5-9102-a9275ecf26cd.JPG)

**Comment by haeyeonlee** [comment]
불러와 줄 객체가 필요한 거 아닐까요?

**Comment by JIHAE-KIM** [comment]
jpanel01이뭔가요???

**Comment by SujiJang** [comment]
아 제가 클래스 불러올 객체를 생성하지 않았내요!! 다시 넣어 해결했습니다!!

**Comment by haeyeonlee** [comment]
앗!!
