### ISSUE TITLE
[#06] add, update, delete, view기능이 한번씩 밖에 수행되지 않아요.

### ISSUE THREAD

**Issue by SujiJang** [JIHAE-KIM/SOFTWARE_JHS#9]
저희 만든 기능이 add, update, delete, view기능이 한번씩 밖에 수행되지 않아요.
각각 데이터베이스에 연결되도록 했는데 뭐가 문제일까요??

**Comment by JIHAE-KIM** [comment]
연결이 각각 끊겨서 그런거아닐까요??
destroy()를 변경해보면될것같아요!!

**Comment by haeyeonlee** [comment]
언니 연결이 끊기는 거 아냐? 클래스 하나를 뺴야하지 않을까?

**Comment by SujiJang** [comment]
아 각각 연결되고 바로 끊기게 했었네요!! destroy()를 이용해서 창이 종료된 후 연결이 끊기도록 변경하였습니다!!
